package com.itaoniu.testserver.persist.pojo;

// Generated 2016-6-28 9:38:42 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TStoreRoleEmployee generated by hbm2java
 */
public class TStoreRoleEmployee implements java.io.Serializable {

	private Long id;
	private String uuid;
	private long storeId;
	private long roleId;
	private long employeeId;
	private Date createTime;
	private Date updateTime;
	private int exist;

	public TStoreRoleEmployee() {
	}

	public TStoreRoleEmployee(String uuid, long storeId, long roleId, long employeeId, Date createTime, Date updateTime, int exist) {
		this.uuid = uuid;
		this.storeId = storeId;
		this.roleId = roleId;
		this.employeeId = employeeId;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.exist = exist;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public long getStoreId() {
		return this.storeId;
	}

	public void setStoreId(long storeId) {
		this.storeId = storeId;
	}

	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

	public long getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(long employeeId) {
		this.employeeId = employeeId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public int getExist() {
		return this.exist;
	}

	public void setExist(int exist) {
		this.exist = exist;
	}

}
